### ISSUE TITLE
Error with JNI (tesseract  ?)

### ISSUE THREAD

**Issue by Jazys** [dreamdragon/text-detection#1]
I think there is some problem with your project.
About tesseract i must include the src folder in jni ?

The problem in DDMS :+1: 
06-21 16:13:43.457: I/DetectText::Activity(912): onCreate
06-21 16:13:43.625: I/Sample::SurfaceView(912): Instantiated new class com.detecttext.DetectView
06-21 16:13:43.665: W/dalvikvm(912): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/detecttext/DetectTextNative;
06-21 16:13:43.665: D/AndroidRuntime(912): Shutting down VM
06-21 16:13:43.675: W/dalvikvm(912): threadid=1: thread exiting with uncaught exception (group=0x40015560)
06-21 16:13:43.727: E/AndroidRuntime(912): FATAL EXCEPTION: main
06-21 16:13:43.727: E/AndroidRuntime(912): java.lang.ExceptionInInitializerError
06-21 16:13:43.727: E/AndroidRuntime(912):  at com.detecttext.DetectText.onCreate(DetectText.java:45)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.os.Handler.dispatchMessage(Handler.java:99)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.os.Looper.loop(Looper.java:123)
06-21 16:13:43.727: E/AndroidRuntime(912):  at android.app.ActivityThread.main(ActivityThread.java:3683)
06-21 16:13:43.727: E/AndroidRuntime(912):  at java.lang.reflect.Method.invokeNative(Native Method)
06-21 16:13:43.727: E/AndroidRuntime(912):  at java.lang.reflect.Method.invoke(Method.java:507)
06-21 16:13:43.727: E/AndroidRuntime(912):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-21 16:13:43.727: E/AndroidRuntime(912):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-21 16:13:43.727: E/AndroidRuntime(912):  at dalvik.system.NativeStart.main(Native Method)
06-21 16:13:43.727: E/AndroidRuntime(912): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load run_detection: findLibrary returned null
06-21 16:13:43.727: E/AndroidRuntime(912):  at java.lang.Runtime.loadLibrary(Runtime.java:429)
06-21 16:13:43.727: E/AndroidRuntime(912):  at java.lang.System.loadLibrary(System.java:554)
06-21 16:13:43.727: E/AndroidRuntime(912):  at com.detecttext.DetectTextNative.<clinit>(DetectTextNative.java:10)
06-21 16:13:43.727: E/AndroidRuntime(912):  ... 14 more
06-21 16:18:43.854: I/Process(912): Sending signal. PID: 912 SIG: 9

So i htink the link with jni isn't correct.
I'm a begiinner in android, and i don't know how to resolve it.

Thanks for your response

**Comment by dreamdragon** [comment]
Hey Jazys, I will take a look at this issue.
